config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html

resources :issues do
  get 'approve', :to => 'quick_update_journal#approve'
  get 'reject', :to => 'quick_update_journal#reject'
  get 'assign_to', :to => 'quick_update_journal#assign_to'
  get 'chmod', :to => 'quick_update_journal#change_mode'
  get 'start', :to => 'quick_update_journal#start'
  get 'pause', :to => 'quick_update_journal#pause'
  get 'finish', :to => 'quick_update_journal#finish'
end

  get 'quick/popup', :to => 'quick_update_journal#popup', :as => 'quick_popup'

  # post 'issues/:task_id/quick/approve', :to => 'quick_update_journal#approve' #for API Later
  post 'quick/approve', :to => 'quick_update_journal#approve', :as => 'quick_approve'
  post 'quick/reject', :to => 'quick_update_journal#reject', :as => 'quick_reject'
  post 'quick/assign_to', :to => 'quick_update_journal#assign_to', :as => 'quick_assign_to'

app/controllers/quick_update_journal_controller.rb
require 'json'

class QuickUpdateJournalController < ApplicationController
  unloadable

  before_filter :find_issue

  helper :issues

  def configs(state)
    file = File.read(Rails.root.to_s + '/plugins/redmine_quick_button_issue/assets/rules/rule_' + state + '.map')
    return JSON.parse(file)
  end

=begin
  TODO list
    rule of approval!
    1. Project & Tracker is defined (it is related with what workflow will be used, and what kind of issue that approval button will show), default will all project + all tracker
    2. issue status is not the last index of workflow
    3. issue status can be excluded for specific condition, but is set none for default
    4. approval process is about change the task status from current status to the next status of workflow
    5. end of approval process will make changes for issue

    Pseudocode:
    projects = @configs[:projects].key
    trackers =

    if @config[:projects].include?(@issue.project) &&
          @issue.tracker == @configs
=end
  def approve
    user = User.current
    assigned_was = @issue.assigned_to
    assigned_new = params[:assigned_to_id]
    status_was = @issue.status
    status_next_available = @issue.new_statuses_allowed_to(User.current)
    notes = params[:notes]

    @configs = configs('approve')
    # Rails.logger.info "Rules of Approval: \n" + @configs.to_s
    @issue.assigned_to_id
  end


=begin
    TODO list
    rule of reject!
    1. Project & Tracker is defined but this followed by approval rule no.1
    2. issue status is not the last index of workflow
    3. issue status can be excluded for specific condition, but is set none for default
    4. issue status for state of rejection must be defined, is should be String and part of last index of workflow. the default will set to any last index of workflow
    5. if next issue status is doesn't have the specific reject status defined, the reject button also should hide
    6. approval process is about change the task status from current status to the last status of workflow
    7. end of reject process will make changes for issue.
=end
  def reject
  end


=begin
    TODO list
    rule of assign_to!
    1. button assign to is should be showing in any state of issue status
    2. assign_to process is may have for any optional rule expression that can configure from plugin configuration, e.g:
      a. change status to "specific_status"
      b. change value of "some_of_specific_attributes_of_issue"
      c. make note is "required" or "optional"
      d. modify any issue variables
=end
  def assign_to
    @issue.assigned_to_id = params[:issue_assigned_to]
    Rails.logger.info "ini issue # \n" + @issue.to_h.to_s
  end

  # UNUSED YET
  # def change_mode
  # end

  # UNUSED YET
  # def start
  # end

  # UNUSED YET
  # def pause
  # end

  # UNUSED YET
  # def finish
  # end

  # UNUSED YET
  # def decline
  # end

  def popup
    respond_to do |format|
      format.js
    end
  end

  ################################################################
  # Below of this comment is used for private method
  ################################################################
  private

  def find_issue
    @issue = Issue.find(params[:task_id])
    raise Unauthorized unless @issue.visible?
    @project = @issue.project

    user_real = User.current
    @status_allowed = @issue.new_statuses_allowed_to(user_real)
    @allowed_approved_status = @status_allowed.select {|status| status[:default_done_ratio] >= 0 && status[:default_done_ratio] < 100 && !status[:name].eql?(@issue.status.to_s) }
    @allowed_rejected_status = @status_allowed.select {|status| status[:is_closed] }

  rescue ActiveRecord::RecordNotFound
    render_404
  end
end

app/helpers/quick_update_journal_helper.rb
module QuickUpdateJournalHelper

  def next_approved_status(issue, user)

  end

  def next_approved_status(&allowed_status)
    allowed_status
  end

  def rejected_status(issue, user)

  end

  def rejected_status(&allowed_status)

  end

  def is_last_state?(issue, user)
    return false
  end

  def is_last_state?(&allowed_status)
    return false
  end

end

app/views/issues/_action_menu.html.erb
<%= javascript_include_tag "redmine_quick_button_issue", :plugin => 'redmine_quick_button_issue' %>
<div class="w-bootstrap-iso">
    <div class="contextual">
        <% if User.current.allowed_to?(:approve_task, @project) && IssueStatus.find(@issue.status)[:default_done_ratio]==0 %>
            <span class="glyphicon glyphicon-ok size-small lightgreen"></span>
            <%= link_to l(:button_approve), quick_popup_path(:task_id=>@issue.id, :task_event => 'approve'), :remote => true %>
        <% end %>
        <% if User.current.allowed_to?(:reject_task, @project)  && IssueStatus.find(@issue.status)[:default_done_ratio]==0%>
            <span class="glyphicon glyphicon-remove size-small red"></span>
            <%= link_to l(:button_reject), quick_popup_path(:task_id=>@issue.id, :task_event => 'reject'), :remote => true %>
        <% end %>
        <% if User.current.allowed_to?(:reassign_task, @project) %>
            <span class="glyphicon glyphicon-user size-small blue-metro"></span>
            <%= link_to l(:button_assign), quick_popup_path(:task_id=>@issue.id, :task_event => 'assign_to'), :remote => true %>
        <% end %>
        <%= link_to l(:button_edit), edit_issue_path(@issue), :onclick => 'showAndScrollTo("update", "issue_notes"); return false;', :class => 'icon icon-edit', :accesskey => accesskey(:edit) if @issue.editable? %>
        <%= link_to l(:button_log_time), new_issue_time_entry_path(@issue), :class => 'icon icon-time-add' if User.current.allowed_to?(:log_time, @project) %>
        <%= watcher_link(@issue, User.current) %>
        <%= link_to l(:button_copy), project_copy_issue_path(@project, @issue), :class => 'icon icon-copy' if User.current.allowed_to?(:add_issues, @project) %>
        <%= link_to l(:button_delete), issue_path(@issue), :data => {:confirm => issues_destroy_confirmation_message(@issue)}, :method => :delete, :class => 'icon icon-del' if User.current.allowed_to?(:delete_issues, @project) %>
    </div>
    <div id="quick-modal" class="hidden"></div>
</div>

app/views/quick_update_journal/_approve.html.erb
<div class="w-bootstrap-iso">
    <%= form_tag({
                     :controller => 'issues',
                     :action => 'update',
                     :id => @issue.id
                 },
                 :method => :put,
                 :id => 'issue-form') do %>
        <div class="form-group">
            <h4>Assign to user:</h4>
            <p class="input-group">
                <span class="input-group-addon" title="Assign to User"><span class=" glyphicon glyphicon-user"></span></span>
                <%= select_tag 'issue[assigned_to_id]', principals_options_for_select(@issue.assignable_users, @issue.assigned_to), :class => 'form-control', "data-live-search" => true, :required => true %>
            </p>
            <% if @allowed_approved_status.size == 1 %>
                <input type="hidden" name="issue[status_id]" value="<%= @allowed_approved_status[0].id %>" />
            <% else %>
                <p class="input-group">
                    <span class="input-group-addon"  title="Set status as"><span class=" glyphicon glyphicon-pencil"></span></span>
                    <%= select_tag 'issue[status_id]', options_from_collection_for_select(@allowed_approved_status, "id", "name"), { :class => 'form-control', "data-live-search" => true, :required => true} %>
                </p>
            <% end %>
            <p><%= link_to 'add note','#', :onclick => 'showComponent("#quick-notes")' %> <small>(optional)</small></p>
            <p><textarea id="quick-notes"  name="issue[notes]" class="form-control hide" rows="3"></textarea></p>
            <p class="text-center">
                <button type="submit" class="btn btn-primary btn-lg" onclick="hideModal(this)"><span class="glyphicon glyphicon-ok"></span> Submit</button>
                <button type="button" class="btn btn-default btn-lg" onclick="hideModal(this)">&#9899; Cancel</button>
            </p>
        </div>
    <% end %>
</div>

app/views/quick_update_journal/_assign_to.html.erb
<div class="w-bootstrap-iso">
    <%= form_tag({
                         :controller => 'issues',
                         :action => 'update',
                         :id => @issue.id
                 },
                 :method => :put,
                 :id => 'issue-form') do %>
        <div class="form-group">
            <h4>Assign to user:</h4>
            <% open_assigned_status_id = 8
               if !@issue.tracker.eql?('Shared Hosted Demo Booking') %>
                <input type="hidden" name="issue[status_id]" value="<%= open_assigned_status_id %>" />
            <% end %>
            <p class="input-group">
                <span class="input-group-addon" title="Assign to User"><span class=" glyphicon glyphicon-user"></span></span>
                <%= select_tag 'issue[assigned_to_id]', principals_options_for_select(@issue.assignable_users, @issue.assigned_to), :class => 'form-control', "data-live-search" => true, :required => true %>
            </p>
            <p><%= link_to 'add note','#', :onclick => 'showComponent("#quick-notes")' %> <small>(optional)</small></p>
            <p><textarea id="quick-notes" class="form-control hide" rows="3" name="issue[notes]"></textarea></p>
            <p class="text-center">
                <button type="submit" class="btn btn-primary btn-lg"><span class="glyphicon glyphicon-ok"></span> Submit</button>
                <button type="button" class="btn btn-default btn-lg" onclick="hideModal(this)">&#9899; Cancel</button>
            </p>
        </div>
    <% end %>
</div>

app/views/quick_update_journal/_reject.html.erb
<div class="w-bootstrap-iso">
    <%= form_tag({
                         :controller => 'issues',
                         :action => 'update',
                         :id => @issue.id
                 },
                 :method => :put,
                 :id => 'issue-form') do %>
        <div class="form-group">
            <div class="alert alert-warning" role="alert"><p><span class="glyphicon glyphicon-exclamation-sign text-x-large yellow-metro"></span> <%= l(:modal_body_reject) %></p></div>
            <% if @allowed_approved_status.size==1 %>
                <input type="hidden" name="issue[status_id]" value="<%= @allowed_rejected_status[0].id %>" />
            <% else %>
                <p class="input-group">
                    <span class="input-group-addon"  title="Set status as"><span class=" glyphicon glyphicon-pencil"></span></span>
                    <%= select_tag 'issue[status_id]', options_from_collection_for_select(@allowed_rejected_status, "id", "name"), { :class => 'form-control', "data-live-search" => true, :required => true} %>
                </p>
            <% end %>
            <p>notes <small>(require)</small></p>
            <p><textarea id="quick-notes"  name="issue[notes]" class="form-control" rows="3" required="required"></textarea></p>
            <p class="text-center">
                <button type="submit" class="btn btn-primary btn-lg"><span class="glyphicon glyphicon-ok"></span> Submit</button>
                <button type="button" class="btn btn-default btn-lg" onclick="hideModal(this)">&#9899; Cancel</button>
            </p>
        </div>
    <% end %>
</div>

app/views/quick_update_journal/popup.js.erb
<%
    modalHeader = case params[:task_event]
        when 'approve' then l(:modal_header_approve)
        when 'reject' then l(:modal_header_reject)
        when 'assign_to' then l(:modal_header_assign_to)
    end
%>
$('#quick-modal').html('<%= escape_javascript(render :partial=>'quick_update_journal/'+params[:task_event].to_s, :locals=>{:issue => @issue, :task_event=> params[:task_event]}) %>');
showModalWithTitle('quick-modal', '600px',"<%= escape_javascript modalHeader + ' #' + @issue.id.to_s %>");
$('#quick-modal').removeClass('hide');

app/views/settings/quick_button/_general.html.erb
<div class="w-bootstrap-iso">
    <div class="container">
        <h3>Action Rules</h3>

        <div id="q-approve">
            <form>

            </form>
        </div>

        <div id="q-reject">
        </div>

    </div>
</div>